drop table if exists role_permissions;
drop table if exists user_roles;
drop table if exists permissions;
drop table if exists roles;
drop table if exists users;

create table users (
    id bigint generated by default as identity primary key,
    name varchar(100) not null,
    username varchar(80) not null unique,
    password varchar(255) not null,
    enabled boolean not null default true,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp
);

create table roles (
    id bigint generated by default as identity primary key,
    code varchar(50) not null unique,
    name varchar(100) not null
);

create table permissions (
    id bigint generated by default as identity primary key,
    code varchar(80) not null unique,
    name varchar(100) not null
);

create table user_roles (
    user_id bigint not null,
    role_id bigint not null,
    primary key (user_id, role_id),
    foreign key (user_id) references users(id),
    foreign key (role_id) references roles(id)
);

create table role_permissions (
    role_id bigint not null,
    permission_id bigint not null,
    primary key (role_id, permission_id),
    foreign key (role_id) references roles(id),
    foreign key (permission_id) references permissions(id)
);
